DATA_ACCOUNT: 14
DATA_FOLDER_PATH: ../../datas/RobustVSDataset_anonymous

HR_INDEX: 0
POWER_READ_INDEX: 1
RADAR_ACCOUNT: 2
RR_INDEX: 1

DRAW_IMAGE: true
MODEL_TRAIN: true
STORE_EXCEL: true
STROE_MODEL: true
Save_model_folder: ../result/Baseline/saved_model/0814-0.2-e1000-test
Save_result_folder: ../result/Baseline/predict_result/0814-0.2-e1000-test
output_excel_name: ../result/Baseline/excel/0814-0.2-e1000-test.xlsx

loss_func: MSE
lstm:
  adaTrain: 1
  batch_size: 8
  dropout: 0.2
  hidden_size: 256
  input_size: 3 # power + distance + move curve
  isBidirectional: true
  num_layers: 2
  nums_ada_epoch: 5
  nums_epoch: 1000
  output_size: 1

smooth: 5