DATA_FOLDER_PATH: ../../datas/cgu

MODEL_TRAIN: true
DRAW_IMAGE: true
STORE_EXCEL: true
STROE_MODEL: false
smooth: false

Save_loss_folder: ../result/CGU/loss/0815-test
Save_model_folder: ../result/CGU/saved_model/0815-test
Save_result_folder: ../result/CGU/predict_result/0815-test
output_excel_name: ../result/CGU/excel/0815-test.xlsx

loss_func: MSE
lstm:
  read_feature: 5 # read input number
  input_size: 4 # lstm in fitness input
  # input_size: 5  # lstm input
  attr_size: 2 # ipaq feature number
  output_size: 1
  batch_size: 8
  dropout: 0.5
  hidden_size: 128  # lstm hidden size in fitness
  # hidden_size: 256 # lstm hidden size

  isBidirectional: true
  num_layers: 2
  nums_epoch: 600