DATA_FOLDER_PATH: ../../datas/cgu
DRAW_IMAGE: true
MODEL_TRAIN: true
STORE_EXCEL: true
STROE_MODEL: true
Save_loss_folder: ../result/CGU/loss/0820_(pdmI)_e5_d300_h256_no_ema
Save_model_folder: ../result/CGU/saved_model/0820_(pdmI)_e5_d300_h256_no_ema
Save_result_folder: ../result/CGU/predict_result/0820_(pdmI)_e5_d300_h256_no_ema
loss_func: MSE
lstm:
  attr_size: 2
  batch_size: 8
  dropout: 0.3
  hidden_size: 256
  input_size: 5
  isBidirectional: true
  num_layers: 2
  nums_epoch: 300
  output_size: 1
  read_feature: 5
output_excel_name: ../result/CGU/excel/0820_(pdmI)_e5_d300_h256_no_ema.xlsx
smooth: 20
